<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  0 => 
  array (
    'name' => '5 digit American general coa',
    'package' => 'chart_en_US-5digit',
    'version' => '2.4.1-5',
    'type' => 'chart',
    'active' => false,
    'path' => 'sql',
    'sql' => 'en_US-new2.sql',
  ),
);
